# Generated by Django 4.2.3 on 2023-09-08 02:19

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=20, null=True, region=None, unique=True, verbose_name='phone number'),
        ),
    ]
