# Generated by Django 4.2.3 on 2023-08-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0002_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='My Gallery Title', max_length=100),
        ),
    ]
