# Generated by Django 4.2.3 on 2023-08-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0003_gallery_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.TextField(default='My gallery description'),
        ),
    ]
