# Generated by Django 4.2.3 on 2023-08-30 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0005_alter_gallery_description_alter_packages_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
