# Generated by Django 4.2.3 on 2023-09-03 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0007_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='package',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserView.packages'),
        ),
    ]
