# Generated by Django 4.2.3 on 2023-09-03 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserView', '0012_alter_bookings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='bookings',
            unique_together={('user', 'package')},
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='time',
        ),
    ]
