# Generated by Django 4.2.3 on 2023-09-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0013_alter_bookings_user_alter_bookings_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='available_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
