# Generated by Django 4.2.3 on 2023-09-06 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0015_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
