# Generated by Django 4.2.3 on 2023-09-08 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0016_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('priceHour', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='packages',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserView.hotel'),
        ),
    ]
