# Generated by Django 4.2.3 on 2023-09-08 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0017_hotel_alter_packages_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='Hotels',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='last_price',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='price',
        ),
    ]
