# Generated by Django 4.2.3 on 2023-09-08 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0018_rename_hotel_hotels_remove_packages_last_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotels',
            old_name='priceHour',
            new_name='priceDay',
        ),
    ]
