# Generated by Django 4.2.3 on 2023-09-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0019_rename_pricehour_hotels_priceday'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='name',
            field=models.CharField(default='Package Name', max_length=50),
        ),
    ]
