# Generated by Django 4.2.3 on 2023-09-08 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0020_packages_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='arrivalDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='packages',
            name='leaveDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
