# Generated by Django 4.2.3 on 2023-09-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0021_packages_arrivaldate_packages_leavedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='sale',
            field=models.FloatField(default=0.0),
        ),
    ]
