# Generated by Django 4.2.3 on 2023-09-08 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0023_plane_packages_plane'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='plane',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserView.plane'),
        ),
    ]
