# Generated by Django 4.2.3 on 2023-09-09 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0024_alter_packages_plane'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserView.hotels'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='plane',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserView.plane'),
        ),
    ]
